PHONY: generate
generate:
	mkdir user_v1
	protoc --go_out=user_v1 --go_opt=paths=source_relative \
			--go-grpc_out=user_v1 --go-grpc_opt=paths=source_relative \
			lib/api/user_v1/service_grpc.proto
