env: "local"

storage:
  host: "localhost"
  port: 5432
  userdb: "postgres"
  password: ""
  dbname: "subusers"
  sslmode: "disable"
http_server:
  address:  "localhost:8080"
  user: "mihail"
