syntax = "proto3";

package user_v1;

option go_package = "NotificationService/pkg/user_v1;user_v1";

service UserV1 {
  rpc CreateNewUser(NewUser) returns (User) {};
  rpc SendNotification(Notification) returns (UserList) {};
}

message NewUser {
  string first_name = 2;
  string last_name = 3;
  string phone_number = 4;
  int32 telegram_id = 5;
  string mail = 6;
}
message User {
  int64 id = 1;
  string first_name = 2;
  string last_name = 3;
  string phone_number = 4;
  int32 telegram_id = 5;
  string mail = 6;
}
message Notification {
  string notification_text = 1;
}
message UserList {
  repeated User users = 1;
}
